<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechProto.proto

namespace Backendservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backendservice.authRequestMessage</code>
 */
class authRequestMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userid = 1;</code>
     */
    private $userid = 0;
    /**
     * Generated from protobuf field <code>int32 clientid = 2;</code>
     */
    private $clientid = 0;

    public function __construct() {
        \GPBMetadata\SpeechProto::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 userid = 1;</code>
     * @return int
     */
    public function getUserid()
    {
        return $this->userid;
    }

    /**
     * Generated from protobuf field <code>int32 userid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserid($var)
    {
        GPBUtil::checkInt32($var);
        $this->userid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 clientid = 2;</code>
     * @return int
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>int32 clientid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkInt32($var);
        $this->clientid = $var;

        return $this;
    }

}

