<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechProto.proto

namespace Backendservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backendservice.authResponseMessage</code>
 */
class authResponseMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string JWT = 1;</code>
     */
    private $JWT = '';

    public function __construct() {
        \GPBMetadata\SpeechProto::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string JWT = 1;</code>
     * @return string
     */
    public function getJWT()
    {
        return $this->JWT;
    }

    /**
     * Generated from protobuf field <code>string JWT = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJWT($var)
    {
        GPBUtil::checkString($var, True);
        $this->JWT = $var;

        return $this;
    }

}

