<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechProto.proto

namespace Backendservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backendservice.SpeechRequest</code>
 */
class SpeechRequest extends \Google\Protobuf\Internal\Message
{
    protected $msg_request;

    public function __construct() {
        \GPBMetadata\SpeechProto::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 3;</code>
     * @return int
     */
    public function getId()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>int32 id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes audioData = 2 [ctype = CORD];</code>
     * @return string
     */
    public function getAudioData()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>bytes audioData = 2 [ctype = CORD];</code>
     * @param string $var
     * @return $this
     */
    public function setAudioData($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMsgRequest()
    {
        return $this->whichOneof("msg_request");
    }

}

