<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speechProto.proto

namespace Backendservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>backendservice.SpeechResponse</code>
 */
class SpeechResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string transcript = 1;</code>
     */
    private $transcript = '';

    public function __construct() {
        \GPBMetadata\SpeechProto::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string transcript = 1;</code>
     * @return string
     */
    public function getTranscript()
    {
        return $this->transcript;
    }

    /**
     * Generated from protobuf field <code>string transcript = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTranscript($var)
    {
        GPBUtil::checkString($var, True);
        $this->transcript = $var;

        return $this;
    }

}

